clusters:
- name: cluster2
  destinationServer: https://kubernetes.default.svc
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"

    sampleApp:
      enabled: true
      branch: HEAD

- name: cluster1
  destinationServer: https://10.13.21.197:6443
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"
    sampleApp:
      enabled: true
      branch: HEAD
