apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy-test
  name: nginx-deploy-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy-test
    spec:
      containers:
      - image: nginx:3300
        name: nginx
        resources: {}
status: {}
